### ISSUE TITLE
В зависимости от окружения менять параметры

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#1]
**Нужно**

1/ Поменять URLs, чтобы поддерживать стейджинг и прод
https://github.com/miptbase/website/commit/5c88fdaa90b8e180b57e5e5989ca6a3c59a4e6f3#diff-93816298ae9f3d2db56d2039c9e6b12d11fd0a336e18c5960a1e3c0e91475095L18

URL меняется в зависимости от окружения

2/ В зависимости от окружения разные ID терминала Тинькофф для эквайринга
Dev — 1611313361029DEMO
Prod — 1611313361029

https://github.com/miptbase/website/commit/46f814f73c220d4010b9bd6603259d1e8c233047

3/ Терминал Paypal (пока можно 2 одинаковых параметра прописать, чтобы потом можно было быстро поменять в исходниках)

**Comment by One1L** [comment]
готово

**Comment by dandaka** [comment]
OG не подойдет такой URL, не по стандарту
нужен полный адрес

![image](https://user-images.githubusercontent.com/2384694/127773649-d8509eba-65fe-432e-ac32-1023b5c67466.png)

**Comment by dandaka** [comment]
И давай заодно избавимся от //miptbase.netlify.app/
у нас теперь стейджинг на dev.miptbase.org

**Comment by One1L** [comment]
Зафиксил

**Comment by dandaka** [comment]
@One1L у меня что-то странное с URL по-прежнему

![image](https://user-images.githubusercontent.com/2384694/127830798-473d42a4-8fdd-4b2c-80f1-f3637d4a6838.png)

**Comment by One1L** [comment]
Запилил переменную с доменом. Для стейджа она равна dev.miptbase.org, для прода miptbase.org

**Comment by dandaka** [comment]
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdev.miptbase.org%2F
всё равно сейчас баги в OG

![image](https://user-images.githubusercontent.com/2384694/128859335-b9fddd9e-57d7-46a0-ad51-557331af703f.png)

**Comment by One1L** [comment]
![image](https://user-images.githubusercontent.com/50299329/128877792-b4b97440-c70f-4fb1-9da3-43f4d6ba1853.png)
