### ISSUE TITLE
Проблемы с перемещением по табам

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#11]
![image](https://user-images.githubusercontent.com/2384694/124435846-ae4b1380-dd75-11eb-9adf-6d1e49fd36de.png)

**Comment by dandaka** [comment]
Давай доделаем правильный порядок перемещения по табам, плз

![image](https://user-images.githubusercontent.com/2384694/126968747-8c68d5e6-8071-4ff2-9574-0f2b446d8746.png)

**Comment by cherdantceva** [comment]
Сделала очередность помещения фокуса. Вопрос, нужно ли делать взаимодействие с элементами в фокусе по клавиатуре. Сейчас у нас например выбор способа оплаты только по клику. Также скрытые поля выбора факультета и года открываются только по клику на "Я учился / учусь в МФТИ". нужно ли сделать так что мы например фокусируемся на этой надписи, нажимаем Enter и разворачиваются поля выбора факультета, и нужно ли делать выбор способа оплаты по Enter
