### ISSUE TITLE
Подключить скрипт Тинькова (и другие платежные скрипты) через lazy load

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#19]
Сейчас

PSI ругается на скрипты

![image](https://user-images.githubusercontent.com/2384694/125287414-2b99f980-e31d-11eb-919c-986ff7447d2f.png)

Как нужно

https://static-tweet.vercel.app/
https://nextjs.org/docs/basic-features/script

До загрузки формы поставить placeholder, который будет индикатором загрузки
типа такого
https://github.com/buildo/react-placeholder

**Comment by One1L** [comment]
готово

**Comment by dandaka** [comment]
У меня всё равно PSI ругается на скрипт Тинькофф, почему?

![image](https://user-images.githubusercontent.com/2384694/127773460-471427f3-9239-4d14-85f0-110f79b550e2.png)
![image](https://user-images.githubusercontent.com/2384694/127773477-dcc377e5-3260-4f41-9c85-568272b45067.png)

**Comment by One1L** [comment]
Ругается потому что эти скрипты загружаются, но не используются. Мы эти скрипты в явном виде не грузим. Мы грузим только основной скрипт тинька, а он в свою очередь грузит эти два, но по какой-то причине не использует

**Comment by dandaka** [comment]
Договорились, что весь компонент Тинька будем загружать через lazy load

**Comment by One1L** [comment]
![image](https://user-images.githubusercontent.com/50299329/129488852-1e6d04b4-bef0-42df-8d19-357bf5a7a083.png)
