### ISSUE TITLE
Фотки доноров развалились

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#28]
![image](https://user-images.githubusercontent.com/2384694/126962600-99cc73f9-8999-4a1b-96ca-10989a9e0ac8.png)

проблема в контенте или в чем? вижу там новые имена

**Comment by cherdantceva** [comment]
оказалось что в файле, откуда стягиваем, статус "Top" был присвоен другим донорам, фотографий которых у нас нет

**Comment by dandaka** [comment]
Ждем решения на уровне контента
