### ISSUE TITLE
Кнопка(и) в форме снизу меняются в зависимости от метода оплаты

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#3]
## Как сейчас

1. Пользователь выбирает метод оплаты
2. Кнопка снизу не изменяется в зависимости от выбора метода оплаты

![image](https://user-images.githubusercontent.com/2384694/123809326-ce9c4d80-d8f1-11eb-8f01-61eabc46a21d.png)

## Как нужно

![image](https://user-images.githubusercontent.com/2384694/123810071-6a2dbe00-d8f2-11eb-8646-2a567a7ed210.png)

1. Пользователь выбирает метод оплаты
2. Кнопка снизу изменяется в зависимости от выбора метода оплаты

Если выбрано "Карта", то показывать кнопки

— Apple Pay + Поддержать проект
— Google Pay + Поддержать проект
— Поддержать проект

Если выбрано "Перевод", то показывать кнопки

— Поддержать проект

Если выбрано "PayPal", то показывать кнопки

— PayPal

**Comment by One1L** [comment]
Готово
