### ISSUE TITLE
Поправить размер текста в ссылках

### ISSUE THREAD

**Issue by Slamshoo** [miptbase/website#66]
![image](https://user-images.githubusercontent.com/4862416/130636388-4cc37a2d-b63c-49f2-a575-c7dfc899c208.png)

**Comment by Slamshoo** [comment]
В макете размер 16 px

**Comment by Slamshoo** [comment]
![image](https://user-images.githubusercontent.com/4862416/130636807-22bac55f-e7ef-4a72-9aba-277c9c6d02ac.png)

**Comment by cherdantceva** [comment]
https://github.com/miptbase/website/issues/50 была задаача на увеличение текста ссылок
