### ISSUE TITLE
В футере на мобиле нет ссылок на страницы

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#69]
Сейчас

Пользователь проматывает до конца страницы и не знает, куда ему отправиться
Нет ссылок в футере на другие страницы

Как нужно

Пользователь проматывает до футера на мобиле и видит ссылки на другие страницы

**Comment by Slamshoo** [comment]
![image](https://user-images.githubusercontent.com/4862416/132211157-70bc25b9-5ae3-449b-9f64-1620f2d458cf.png)
Подготовоил дизайн футера мобилной версии
