### ISSUE TITLE
Переделать карточки на странице Доноров

### ISSUE THREAD

**Issue by Slamshoo** [miptbase/website#73]
![image](https://user-images.githubusercontent.com/4862416/130949798-510c5935-c5a0-4bb3-b43c-6cc94e8d7802.png)

**Comment by cherdantceva** [comment]
Доноры сортируются в зависимости от класса по убыванию

**Comment by dandaka** [comment]
@cherdantceva 

![telegram-cloud-photo-size-2-5298750717454039312-y](https://user-images.githubusercontent.com/2384694/132244994-ae012c9c-3a86-4fd5-88f4-b0f70bd2b1c4.jpg)

Есть 2 группы доноров — крупные и мелкие. Они верно изображены как I и II на твоём рисунке. Они же классы A и B в Гугл-доке.

Крупных доноров мы показываем с фоткой (если есть) или дефолтной заглушкой (если нет).

Мелких доноров мы показываем меньшими блоками без фоток в любом случае.

И сортировка доноров должна идти так, как она идет в Гугл табличке.
