### ISSUE TITLE
Поменять заголовок на странице Доноры

### ISSUE THREAD

**Issue by dandaka** [miptbase/website#86]
Сейчас

https://dev.miptbase.org/donors
"Эндаумент привлек 22 млн ₽ за полгода"

Нужно

1. Берем общую сумму пожертвований с главной страницы (34.9 млн ₽ всего пожертвований)
2. Округляем до целых миллионов
3. Меняем текст на "Эндаумент привлек 35 млн ₽ за X месяцев"
4. X месяцев вычисляем как разницу между текущей датой и 28 января 2021

**Comment by Sergey-Beltsin** [comment]
pushed in develop
